openapi: "3.0.0"
info:
  version: 1.0.0
  title: Ecommerce
  license:
    name: MIT
servers:
  - url: http://example.com/v1/api
paths:
  /orders:
    get:
      summary: List all orders of the authenticated user.
      operationId: listOrders
      tags:
        - orders
      responses:
        '200':
          description: An array of orders
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
  /orders/{orderId}/items/{itemId}:
    get:
      summary: Shows an item of a given order.
      operationId: showItem
      tags:
        - items
      parameters:
        - name: orderId
          in: path
          required: true
          description: The id of an order.
          schema:
            type: integer
        - name: itemId
          in: path
          required: true
          description: The id of an item.
          schema:
            type: integer
      responses:
        '200':
          description: An item belonging to an order.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
components:
  schemas:
    Order:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Orders:
      type: array
      items:
        $ref: "#/components/schemas/Order"
    Item:
      required:
        - id
        - name
        - qty
        - price
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        qty:
          type: integer
          format: int64
        price:
          type: float
