openapi: 3.0.3
info:
  title: Orders
  description: API that allows a seller to obtain information about orders received in a marketplace. Inspired by Amazon's Selling Partner API for Orders.
  version: 1.0.0
servers:
  - url: https://example.com/orders
paths:
  /READORDERS:
    get:
      summary: List all orders received.
      operationId: list_orders
      tags:
        - orders
      responses:
        200:
          description: An array of orders
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
  /order_cancellation:
    post:
      summary: Creates an order cancellation (i.e., cancels a given order)
      operationId: order_cancellation
      tags:
        - orders
      responses:
        201:
          description: Confirmation that the order was cancelled.
  /orders/{order_id}/buyer_info:
    post:
      summary: Retrieves the buyer information for a given order.
      operationId: get_buyer_info
      tags:
        - orders
        - buyer_info
      parameters:
        - name: order_id
          in: path
          required: true
          description: The id of an order.
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Buyer"
components:
  schemas:
    Buyer:
      description: The buyer of an order.
      required:
        - email
        - name
      properties:
        email:
          description: The email of the buyer.
          type: string
        name:
          description: The name of the buyer.
          type: string
    Order:
      description: An order.
      required:
        - id
        - total
      properties:
        id:
          description: The unique identifier of an order.
          type: integer
          format: int64
        total:
          description: The order's total in cents.
          type: integer
          format: int64
    Orders:
      description: A collection of orders.
      type: array
      items:
        $ref: "#/components/schemas/Order"
