openapi: 3.0.3
info:
  title: Payments Provider API.
  description: API that allows one to charge customers via credit card. Inspired by Stripe's API.
  version: '0.1'
servers:
  - url: http://example.com/v1/api
paths:
  /charges:
    post:
      summary: Creates a new charge.
      operationId: create_charge
      tags:
        - charges
      requestBody:
        description: The charge to be created.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Charge"
      responses:
        '200':
          description: An error occurred and the charge was not created.
          content:
            schema:
              $ref: "#/components/schemas/ChargeError"
        '201':
          description: The charge was successfully created.

  /charges/{charge_id}:
    post:
      summary: Shows details on a given charge.
      operationId: show_charge
      tags:
        - charges
      parameters:
        - name: charge_id
          in: path
          required: true
          description: The id of a charge.
          schema:
            type: integer
      responses:
        '200':
          description: Details of a charge.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Charge"
components:
  schemas:
    Charge:
      description: A charge.
      required:
        - amount
        - currency
        - credit_card_id
      properties:
        id:
          description: The unique identifier of a charge.
          type: integer
          format: int64
        amount:
          description: The amount to be charged.
          type: number
          format: double
        currency:
          description: Three-letter ISO currency code.
          type: string
        credit_card_id:
          description: The credit card to be charged.
          type: integer
          format: int64
    ChargeError:
      description: Represents an error occurred while trying to create a charge.
      properties:
        message:
          description: The description of the error.
          type: string
